services:
  gbfapp:
    image: quak1/chuy-gbf:latest
    container_name: chuy-gbf
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - data:/data

volumes:
  data:
