// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: db.sql

package store

import (
	"context"
)

const addDBDataUpdate = `-- name: AddDBDataUpdate :exec
INSERT INTO db_data_updates (is_ok, comments)
VALUES (?, ?)
`

type AddDBDataUpdateParams struct {
	IsOk     bool   `json:"is_ok"`
	Comments string `json:"comments"`
}

func (q *Queries) AddDBDataUpdate(ctx context.Context, arg AddDBDataUpdateParams) error {
	_, err := q.db.ExecContext(ctx, addDBDataUpdate, arg.IsOk, arg.Comments)
	return err
}

const getAllDBDataUpdates = `-- name: GetAllDBDataUpdates :many
SELECT id, is_ok, comments, created_at FROM db_data_updates
`

func (q *Queries) GetAllDBDataUpdates(ctx context.Context) ([]DbDataUpdate, error) {
	rows, err := q.db.QueryContext(ctx, getAllDBDataUpdates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DbDataUpdate
	for rows.Next() {
		var i DbDataUpdate
		if err := rows.Scan(
			&i.ID,
			&i.IsOk,
			&i.Comments,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLastDBDataUpdate = `-- name: GetLastDBDataUpdate :one
SELECT id, is_ok, comments, created_at FROM db_data_updates
WHERE is_ok = 1
ORDER BY id DESC
LIMIT 1
`

func (q *Queries) GetLastDBDataUpdate(ctx context.Context) (DbDataUpdate, error) {
	row := q.db.QueryRowContext(ctx, getLastDBDataUpdate)
	var i DbDataUpdate
	err := row.Scan(
		&i.ID,
		&i.IsOk,
		&i.Comments,
		&i.CreatedAt,
	)
	return i, err
}
