// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: items.sql

package store

import (
	"context"
)

const createItem = `-- name: CreateItem :exec
INSERT INTO items (id, name, element, type, series, enabled)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO NOTHING
`

type CreateItemParams struct {
	ID      string `json:"id"`
	Name    string `json:"name"`
	Element string `json:"element"`
	Type    string `json:"type"`
	Series  string `json:"series"`
	Enabled bool   `json:"enabled"`
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) error {
	_, err := q.db.ExecContext(ctx, createItem,
		arg.ID,
		arg.Name,
		arg.Element,
		arg.Type,
		arg.Series,
		arg.Enabled,
	)
	return err
}

const getAllItems = `-- name: GetAllItems :many
SELECT id, name, element, type, series, enabled FROM items
`

func (q *Queries) GetAllItems(ctx context.Context) ([]Item, error) {
	rows, err := q.db.QueryContext(ctx, getAllItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Element,
			&i.Type,
			&i.Series,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
