// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: items.sql

package store

import (
	"context"
)

const createItem = `-- name: CreateItem :exec
INSERT OR REPLACE INTO items (id, name, element, type, series, enabled, category)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateItemParams struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Element  string `json:"element"`
	Type     string `json:"type"`
	Series   string `json:"series"`
	Enabled  bool   `json:"enabled"`
	Category string `json:"category"`
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) error {
	_, err := q.db.ExecContext(ctx, createItem,
		arg.ID,
		arg.Name,
		arg.Element,
		arg.Type,
		arg.Series,
		arg.Enabled,
		arg.Category,
	)
	return err
}

const createItemValue = `-- name: CreateItemValue :one
INSERT INTO item_values  (item_id, value, color)
VALUES (?, ?, ?)
RETURNING id, item_id, value, color
`

type CreateItemValueParams struct {
	ItemID string `json:"item_id"`
	Value  string `json:"value"`
	Color  string `json:"color"`
}

func (q *Queries) CreateItemValue(ctx context.Context, arg CreateItemValueParams) (ItemValue, error) {
	row := q.db.QueryRowContext(ctx, createItemValue, arg.ItemID, arg.Value, arg.Color)
	var i ItemValue
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.Value,
		&i.Color,
	)
	return i, err
}

const deleteItemValue = `-- name: DeleteItemValue :exec
DELETE FROM item_values WHERE id = ? AND item_id = ?
`

type DeleteItemValueParams struct {
	ID     int64  `json:"id"`
	ItemID string `json:"item_id"`
}

func (q *Queries) DeleteItemValue(ctx context.Context, arg DeleteItemValueParams) error {
	_, err := q.db.ExecContext(ctx, deleteItemValue, arg.ID, arg.ItemID)
	return err
}

const disableItem = `-- name: DisableItem :exec
UPDATE items
SET enabled = 0
WHERE id = ?
`

func (q *Queries) DisableItem(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, disableItem, id)
	return err
}

const enableItem = `-- name: EnableItem :exec
UPDATE items
SET enabled = 1
WHERE id = ?
`

func (q *Queries) EnableItem(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, enableItem, id)
	return err
}

const getAllItems = `-- name: GetAllItems :many
SELECT id, name, element, type, series, enabled, category FROM items
`

func (q *Queries) GetAllItems(ctx context.Context) ([]Item, error) {
	rows, err := q.db.QueryContext(ctx, getAllItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Element,
			&i.Type,
			&i.Series,
			&i.Enabled,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllSelectedItemValues = `-- name: GetAllSelectedItemValues :many
SELECT ui.user_id, iv.id AS value_id, iv.item_id, iv.value, iv.color FROM user_items ui
JOIN item_values iv ON ui.item_value_id = iv.id
`

type GetAllSelectedItemValuesRow struct {
	UserID  int64  `json:"user_id"`
	ValueID int64  `json:"value_id"`
	ItemID  string `json:"item_id"`
	Value   string `json:"value"`
	Color   string `json:"color"`
}

func (q *Queries) GetAllSelectedItemValues(ctx context.Context) ([]GetAllSelectedItemValuesRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllSelectedItemValues)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllSelectedItemValuesRow
	for rows.Next() {
		var i GetAllSelectedItemValuesRow
		if err := rows.Scan(
			&i.UserID,
			&i.ValueID,
			&i.ItemID,
			&i.Value,
			&i.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEnabledItems = `-- name: GetEnabledItems :many
SELECT id, name, element, type, series, enabled, category FROM items
WHERE enabled = 1
`

func (q *Queries) GetEnabledItems(ctx context.Context) ([]Item, error) {
	rows, err := q.db.QueryContext(ctx, getEnabledItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Element,
			&i.Type,
			&i.Series,
			&i.Enabled,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItemValues = `-- name: GetItemValues :many
SELECT id, item_id, value, color FROM item_values
WHERE item_id = ?
`

func (q *Queries) GetItemValues(ctx context.Context, itemID string) ([]ItemValue, error) {
	rows, err := q.db.QueryContext(ctx, getItemValues, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ItemValue
	for rows.Next() {
		var i ItemValue
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.Value,
			&i.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
