// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: items.sql

package store

import (
	"context"
)

const createItem = `-- name: CreateItem :exec
INSERT OR REPLACE INTO items (id, name, element, type, series, enabled, category)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateItemParams struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Element  string `json:"element"`
	Type     string `json:"type"`
	Series   string `json:"series"`
	Enabled  bool   `json:"enabled"`
	Category string `json:"category"`
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) error {
	_, err := q.db.ExecContext(ctx, createItem,
		arg.ID,
		arg.Name,
		arg.Element,
		arg.Type,
		arg.Series,
		arg.Enabled,
		arg.Category,
	)
	return err
}

const disableItem = `-- name: DisableItem :exec
UPDATE items
SET enabled = 0
WHERE id = ?
`

func (q *Queries) DisableItem(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, disableItem, id)
	return err
}

const enableItem = `-- name: EnableItem :exec
UPDATE items
SET enabled = 1
WHERE id = ?
`

func (q *Queries) EnableItem(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, enableItem, id)
	return err
}

const getAllItems = `-- name: GetAllItems :many
SELECT id, name, element, type, series, enabled, category FROM items
`

func (q *Queries) GetAllItems(ctx context.Context) ([]Item, error) {
	rows, err := q.db.QueryContext(ctx, getAllItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Element,
			&i.Type,
			&i.Series,
			&i.Enabled,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEnabledItems = `-- name: GetEnabledItems :many
SELECT id, name, element, type, series, enabled, category FROM items
WHERE enabled = 1
`

func (q *Queries) GetEnabledItems(ctx context.Context) ([]Item, error) {
	rows, err := q.db.QueryContext(ctx, getEnabledItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Element,
			&i.Type,
			&i.Series,
			&i.Enabled,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserItemValues = `-- name: GetUserItemValues :many
SELECT user_id, item_id, value FROM user_items
`

func (q *Queries) GetUserItemValues(ctx context.Context) ([]UserItem, error) {
	rows, err := q.db.QueryContext(ctx, getUserItemValues)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserItem
	for rows.Next() {
		var i UserItem
		if err := rows.Scan(&i.UserID, &i.ItemID, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
