// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

type Item struct {
	ID      string
	Name    string
	Element string
	Type    string
	Series  string
	Enabled bool
}
