// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

type Item struct {
	ID      string `json:"id"`
	Name    string `json:"name"`
	Element string `json:"element"`
	Type    string `json:"type"`
	Series  string `json:"series"`
	Enabled bool   `json:"enabled"`
}

type User struct {
	ID      int64  `json:"id"`
	Name    string `json:"name"`
	Comment string `json:"comment"`
	Role    string `json:"role"`
}
