// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package store

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, comment, role)
VALUES (?, "", ?)
ON CONFLICT(username) DO UPDATE SET username = username
RETURNING id, username, role
`

type CreateUserParams struct {
	Username string `json:"username"`
	Role     string `json:"role"`
}

type CreateUserRow struct {
	ID       int64  `json:"id"`
	Username string `json:"username"`
	Role     string `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Username, arg.Role)
	var i CreateUserRow
	err := row.Scan(&i.ID, &i.Username, &i.Role)
	return i, err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, username, comment FROM users
WHERE role != "admin"
`

type GetAllUsersRow struct {
	ID       int64  `json:"id"`
	Username string `json:"username"`
	Comment  string `json:"comment"`
}

func (q *Queries) GetAllUsers(ctx context.Context) ([]GetAllUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllUsersRow
	for rows.Next() {
		var i GetAllUsersRow
		if err := rows.Scan(&i.ID, &i.Username, &i.Comment); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT id, username, comment, role FROM users
WHERE id = ?
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Comment,
		&i.Role,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, comment, role FROM users
WHERE username = ?
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Comment,
		&i.Role,
	)
	return i, err
}

const getUserItems = `-- name: GetUserItems :many
SELECT
  i.id, i.name, i.element, i.type, i.series, i.enabled, i.category,
  COALESCE(iv.id, 0) AS item_value_id,
  COALESCE(iv.value, '') AS value,
  COALESCE(iv.color, '') AS color
FROM items i
LEFT JOIN user_items ui ON ui.item_id = i.id AND ui.user_id = ?
LEFT JOIN item_values iv ON iv.id = ui.item_value_id
WHERE i.enabled = 1
`

type GetUserItemsRow struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Element     string `json:"element"`
	Type        string `json:"type"`
	Series      string `json:"series"`
	Enabled     bool   `json:"enabled"`
	Category    string `json:"category"`
	ItemValueID int64  `json:"item_value_id"`
	Value       string `json:"value"`
	Color       string `json:"color"`
}

func (q *Queries) GetUserItems(ctx context.Context, userID int64) ([]GetUserItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserItems, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserItemsRow
	for rows.Next() {
		var i GetUserItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Element,
			&i.Type,
			&i.Series,
			&i.Enabled,
			&i.Category,
			&i.ItemValueID,
			&i.Value,
			&i.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const makeUserAdmin = `-- name: MakeUserAdmin :exec
UPDATE users
SET role = "admin"
WHERE id = ?
`

func (q *Queries) MakeUserAdmin(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, makeUserAdmin, id)
	return err
}

const removeUserRole = `-- name: RemoveUserRole :exec
UPDATE users
SET role = ""
WHERE id = ?
`

func (q *Queries) RemoveUserRole(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, removeUserRole, id)
	return err
}

const setUserComment = `-- name: SetUserComment :exec
UPDATE users
SET comment = ?
WHERE id = ?
`

type SetUserCommentParams struct {
	Comment string `json:"comment"`
	ID      int64  `json:"id"`
}

func (q *Queries) SetUserComment(ctx context.Context, arg SetUserCommentParams) error {
	_, err := q.db.ExecContext(ctx, setUserComment, arg.Comment, arg.ID)
	return err
}

const setUserItem = `-- name: SetUserItem :exec
INSERT INTO user_items (user_id, item_id, item_value_id)
VALUES (?, ?, ?)
ON CONFLICT DO UPDATE SET item_value_id = excluded.item_value_id
`

type SetUserItemParams struct {
	UserID      int64  `json:"user_id"`
	ItemID      string `json:"item_id"`
	ItemValueID int64  `json:"item_value_id"`
}

func (q *Queries) SetUserItem(ctx context.Context, arg SetUserItemParams) error {
	_, err := q.db.ExecContext(ctx, setUserItem, arg.UserID, arg.ItemID, arg.ItemValueID)
	return err
}
